### ISSUE TITLE
使用插件遇到的问题和不解之处

### ISSUE THREAD

**Issue by evan0204** [Timson020/react-native-wx-ali-pay#5]
按照文档说明设置后，build ios/android都无问题。
使用上alipay支付宝存在一个问题，如果是直接按照文档中所说使用的话，会报错，错误为：无法转换为String类型。
我调用成功的代码：
`export function aliPay(payParams, callBack = () => {}) {
  Pay.onAliPay(JSON.stringify(payParams))
    .then(e => callBack(e))
    .catch(err => Toast.fail(err));
}`
和作者的使用区别就是：转换了以下json参数为String字符串：JSON.stringify(payParams)

调用时我使用的是test数据(各参数结构正确，参数值随手填的无效数据)，当跳转到支付端提示错误后返回到自己APP中会报错，引起APP的Crash(IOS/Android都会出现)。希望作者可以修复下。

另外在设置xcode工程时候，设置URL Scheme 为：testWXPay，总感觉test的命名有风险不敢在正式环境中使用，我查了下其他支付lib的说明：
> 设置 URL Scheme URL Scheme是通过系统找到并跳转对应app的设置，通过向项目中的info.plist文件中加入URL types可使用第三方平台所注册的appkey信息向系统注册你的app，当跳转到第三方应用支付后，可直接跳转回你的app。微信填写微信ID,支付宝也建议添加ap+加支付宝应用id的形式以免冲突。

但是并没有看懂，好想支付宝没有设置此参数也没有问题，可以正常跳转回来，希望可以给予比较详细的答复或者追加到 readme上。谢谢！

**Comment by Timson020** [comment]
# 使用alipay的方式

在md上和源码上有点出入, 只需要传入后端返回的string即可

# 关于URL Scheme

我会在下个版本修改一下

**Comment by Timson020** [comment]
## Fixed the url scheme
+ close #5
